FROM python:3.13-slim-bookworm

# Set working directory
WORKDIR /app

# Copy all project files into container
COPY . /app/

# Install system dependencies
RUN apt-get update -y && apt-get install -y awscli -y

# Install Python dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expose FastAPI port 
EXPOSE 8000

# Command to run the app
CMD ["python3", "app.py"]